# ===== simu =====
seed: 0

simulation:
  max_agents: 128
  init_agents: 16
  birth_pool_size: 8
  wall_effect: "none"

logging:
  wandb_log: false
  sampling_freq: 
  sampling_size: 4
  ckpt_freq: 
  wandb_project: "eedx_dev"


# ===== chemical types =====

ct-1: 
  diffusion_rate: 1.0
  is_sparse: true
  emission_rate: 0.1

# ===== food types =====

ft-1:
  growth_rate: 0.0
  dmin: 1
  dmax: 1
  chemical_signature: 0
  energy_concentration: 1.0
  spontaneous_grow_prob: 0.0
  initial_density: 0.1


# ===== env =====

env:
  size: [128,128]
  chemicals_detection_threshold: 0.001
  walls_density: 0.0

# ===== agents =====

agents:

  body_resolution: 4
  init_energy: 0.5
  max_energy: 50.0
  basal_energy_loss: 1.0
  size_energy_cost: 0.0
  reproduction_energy_cost: 0.5
  time_above_threshold_to_reproduce: 150
  time_below_threshold_to_die: 100
  min_body_size: 1.0
  max_body_size: 10.0
  max_age: 1000

  motor:
    which: "braitenberg"
    interface: "direct"
    max_wheel_speed: 8.0
    wheel_speed_gain: 0.5
    motor_energy_cost: 0.1
    dt: 0.1

  sensory:
    which: "flatten"
    subset: "front"

  nn:
    which: "ctrnn"

  mutation:
    which: "generalized"
    sigma: 0.03
    p_mut: 0.01







